### ISSUE TITLE
Add specific duration of the toast

### ISSUE THREAD

**Issue by GustavoCostaW** [EddyVerbruggen/Toast-PhoneGap-Plugin#59]
It's possible add specific duration of the toast

ex:

.show('message','5000','bottom'); //5 seconds to end toast

**Comment by napcat** [comment]
+1

Can it be possible?

**Comment by sindris12** [comment]
+1 this would be awesome

**Comment by cezarcruz** [comment]
+1

**Comment by cezarcruz** [comment]
[http://www.x-services.nl/phonegap-toast-plugin/796](http://www.x-services.nl/phonegap-toast-plugin/796)
Showing the Toast a bit longer

When you want to display more than a few words, you’ll want to show the Toast a bit longer. So I also need a ‘duration’ parameter. Since Android only supports ‘short’ (2 seconds) and ‘long’ (5 seconds), we have to settle with that. Note that you can use an arbitrary length on iOS, but I like uniform API’s.

**Comment by EddyVerbruggen** [comment]
I've had a TODO for this at the top of the Android impl class for ages, I'll pick this up now!

**Comment by EddyVerbruggen** [comment]
Available in 2.5.0 (will release later today). See the readme for usage.
